[package]
name = "libcx"
version = "0.1.0"
edition = "2021"

[dependencies]
# 添加libc的依赖后，就不需要再重复地一个个声明系统函数了
libc = "0.2.119"
system-call = { path = "../system-call" }

[dev-dependencies]
open-coroutine = { path = "../open-coroutine" }
open-coroutine-scheduler = { path = "../scheduler" }