[package]
name = "open-coroutine"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
memory-pool = { path = "memory-pool" }

[build-dependencies]
cc = "1.0.73"
rustversion = "1.0.6"

[workspace]
members = [
    "memory-pool",
]