[package]
name = "open-coroutine-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
object-list = { path = "../object-list" }
timer = { path = "../timer" }
open-coroutine = { path = "../open-coroutine" }
lazy_static = "1.4.0"